project:
  type: website
  output-dir: docs
  
website:
  title: "Learning with Quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/Nat-Stephenson/ActiveLearning-Website
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Nat-S"

format:
  html:
    theme: minty
    toc: true

editor: source

